### ISSUE TITLE
Where is the code that checks incoming payments of an address?

### ISSUE THREAD

**Issue by naddika** [woodser/monero-deposit-viewer#7]
There's a lot of code. Where is the gist of extracting or checking balance of an address, for incoming payments?

**Comment by woodser** [comment]
After [creating a wallet](https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/creating_wallets.md), you can get the balance of specific subaddress with [wallet.getBalance()](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#getBalance), e.g.:

```
// get the balance of account 0, subaddress 1
let balance = await wallet.getBalance(0, 1);
```

To get incoming transfers to a specific subaddress, use [wallet.getTransfers()](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#getTransfers), e.g.:

```
// get incoming transfers to account 0, subaddress 1
let transfers = await wallet.getTransfers({
  isIncoming: true,
  accountIndex: 0,
  subaddressIndex: 1
});

// or get incoming transfers to a subaddress
let transfers = await wallet.getTransfers({
  isIncoming: true,
  address: "54mANzvpz..."
});
```

**Comment by woodser** [comment]
I realized my answer was specific to the monero-javascript library and not in the context of this tool (note this tool isn't built yet, it's currently a clone of another tool).

But essentially to build this tool, one first creates a view-only wallet with the wallet's primary address, private view key, and restore height:

```
// create and sync view-only wallet
let viewOnlyWallet = await monerojs.createWalletFull({
  path: "my_view_only_wallet",
  networkType: "stagenet",
  primaryAddress: "55bcxMRhBWea6xxsot8moF1rdPprjJR2x4mfnNnTGgBJFgXa4gWXmWAYdUBKiRcJxy9AUAGJEg28DejvWdJU2VgUDrUvCHG",
  privateViewKey: "03d463f03ae547b11dfdf194a07ff82c14a3c6a3de559bd89c9a5e8dc5e9ae02",
  restoreHeight: 573936,
  server: {uri: "http://localhost:38081", username: "superuser", password: "abctesting123"}
});
await viewOnlyWallet.sync();
```

Then incoming transfers can be retrieved with [getTransfers()](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#getTransfers) as documented above.

**Comment by woodser** [comment]
Closing. Please let me know if you have further questions.
